---
- name: Gather facts
  hosts: localhost
  gather_facts: true
  connection: local

- name: Create an rtmpServer
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - vars/ec2-vars.yaml
  tasks:
    - name: Gather information about rtmpServer instances
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Name": rtmpServer
      register: ec2
      failed_when: false

    - debug: var=ec2

    - name: Terminate rtmpServer instances
      amazon.aws.ec2:
        region: "{{ ec2_region }}"
        state: absent
        instance_ids: "{{ ec2.instances | map(attribute='instance_id') | list }}"
