# CloudStream Copyright (C) 2020  Kevin Carter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---

- name: Set python interpreter fact
  set_fact:
    ansible_python_interpreter: "{{ local_python_interpreter }}"
  when:
    - local_python_interpreter is defined

- name: "Create ssh key"
  community.digitalocean.digital_ocean_sshkey:
    name: "{{ droplet_keypair }}"
    ssh_pub_key: "{{ lookup('file', ansible_env.HOME ~ '/.ssh/id_rsa.pub') }}"
    state: present
  register: ssh_key

- name: Create a new droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: rtmpServer
    unique_name: true
    size:  "{{ droplet_instance_type }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    wait_timeout: 600
    ssh_keys:
    - "{{ ssh_key.data.ssh_key.id }}"
  register: my_droplet

- name: Add instance to dynamic group
  add_host:
    hostname: "{{ my_droplet.data.droplet.id }}"
    ansible_host: "{{ my_droplet.data.ip_address }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    groups:
    - streamerTarget

- name: Wait for ssh to come up
  wait_for:
    host: "{{ my_droplet.data.ip_address }}"
    port: 22
    delay: 10
    timeout: 300
