# CloudStream Copyright (C) 2020  Kevin Carter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---

- name: Set python interpreter fact
  set_fact:
    ansible_python_interpreter: "{{ local_python_interpreter | default('/usr/bin/python3') }}"
  when:
    - local_python_interpreter is defined

- name: Run a droplet by tag search
  uri:
    url: https://api.digitalocean.com/v2/droplets?tag_name=rtmpServer
    method: GET
    return_content: yes
    body_format: json
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ lookup('env', 'DO_API_KEY') }}"
  register: droplets_info

- name: Destroy rtmpServer droplet(s)
  community.digitalocean.digital_ocean_droplet:
    state: absent
    id: "{{ item.id }}"
    unique_name: true
    size:  "{{ droplet_instance_type }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    wait_timeout: 600
  loop: "{{ droplets_info.json.droplets }}"
  loop_control:
    label: "{{ item.name }}"
