# CloudStream Copyright (C) 2020  Kevin Carter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---

- name: Configure the rtmp server
  hosts: streamerTarget
  gather_facts: true
  collections:
    - peznauts.cloudstream
  roles:
    - role: nginx_rtmp_server
  pre_tasks:
    - name: Dump Inventory
      run_once: true
      connection: local
      copy:
        content: |-
          {% set inv = {
               "all": {
                 "children": {
                   "topologyMap": {
                     "hosts": {}
                   },
                   "transcodeTopologyMap": {
                     "hosts": {}
                   },
                   "streamerTarget": {
                     "hosts": {}
                   }
                 }
               }
             }
          %}
          {% for item in groups['topologyMap'] %}
          {%
               set _ = inv['all']['children']['topologyMap']['hosts'].__setitem__(
                 item,
                 hostvars[item]
               )
          %}
          {% endfor %}
          {% for item in groups['streamerTarget'] | default([]) %}
          {%
               set _ = inv['all']['children']['streamerTarget']['hosts'].__setitem__(
                 item,
                 hostvars[item]
               )
          %}
          {% endfor %}
          {% for item in groups['transcodeTopologyMap'] | default([]) %}
          {%
               set _ = inv['all']['children']['transcodeTopologyMap']['hosts'].__setitem__(
                 item,
                 hostvars[item]
               )
          %}
          {%   for key, values in hostvars[item]['groups'].items() %}
          {%     for value_item in values %}
          {%       if inv['all']['children'][key] is defined %}
          {%
                   set _ = inv['all']['children'][key]['hosts'].__setitem__(
                     key,
                     value_item
                   )
          %}
          {%       else %}
          {%
                   set _ = inv['all']['children'].__setitem__(
                     key,
                     {
                       "hosts": {value_item: {}}
                     }
                   )
          %}
          {%       endif %}
          {%     endfor %}
          {%   endfor %}
          {% endfor %}
          {{ inv | to_nice_yaml }}
        dest: /tmp/local-inventory.yaml
  post_tasks:
    - name: Get stats of the FS object
      ansible.builtin.stat:
        path: Untitled/service.json
      register: service_json

    - name: Service block
      when:
        - service_json.stat.exists | bool
      block:
        - name: Create service json for custom RTMP Stream
          copy:
            content: |-
              {
                  "settings": {
                      "bwtest": false,
                      "key": "",
                      "server": "rtmp://{{ hostvars['rtmpServer-main']['ansible_host'] }}:1935/simulcast",
                      "use_auth": false
                  },
                  "type": "rtmp_custom"
              }
            dest: Untitled/service.json
        - name: Notice
          debug:
            msg: >-
              OBS has been configured with the new stream RTMP setup.
              If OBS is running please restart it now.
              The changes will go into effect on the next restart.
    - name: Print Stream URL
      debug:
        msg: >-
          This is the new stream URL:
          rtmp://{{ hostvars['rtmpServer-main']['ansible_host'] }}:1935/simulcast
          To use this URL you must setup a custom stream type.
      run_once: true
      when:
        - not (service_json.stat.exists | bool)
